name: Package NuGet
on:
  push:
    branches: [main]

jobs:
  package-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore  # Sin ruta específica, restaura todos los proyectos

      - name: Run Unit Tests
        run: dotnet test  # Ejecuta todos los tests

      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectKey: nestor123_nestor
          organization: Nestor123
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Pack NuGet package
        run: dotnet pack -c Release -o ./nuget  # Empaqueta todos los proyectos packables

      - name: Publish NuGet package to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./nuget/*.nupkg
          token: ${{ secrets.GITHUB_TOKEN }}